// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuryoyoBibliotek.Data;

#nullable disable

namespace SuryoyoBibliotek.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231205124926_intialize4")]
    partial class intialize4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<int>("AuthorsAuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BooksBookID")
                        .HasColumnType("int");

                    b.HasKey("AuthorsAuthorId", "BooksBookID");

                    b.HasIndex("BooksBookID");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookID"));

                    b.Property<string>("BookTitle")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<Guid>("Isbn")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LoanCardId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Loaned")
                        .HasColumnType("bit");

                    b.Property<int?>("RentalCardsRentalCardId")
                        .HasColumnType("int");

                    b.Property<int?>("RentalYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BookID");

                    b.HasIndex("RentalCardsRentalCardId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.RentalCard", b =>
                {
                    b.Property<int>("RentalCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalCardId"));

                    b.Property<int>("RentalCardPin")
                        .HasColumnType("int");

                    b.HasKey("RentalCardId");

                    b.ToTable("RentedCards");
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("RentalCardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RentalCardId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("SuryoyoBibliotek.Model.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuryoyoBibliotek.Model.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.Book", b =>
                {
                    b.HasOne("SuryoyoBibliotek.Model.RentalCard", "RentalCards")
                        .WithMany("Books")
                        .HasForeignKey("RentalCardsRentalCardId");

                    b.Navigation("RentalCards");
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.User", b =>
                {
                    b.HasOne("SuryoyoBibliotek.Model.RentalCard", "RentalCard")
                        .WithMany()
                        .HasForeignKey("RentalCardId");

                    b.Navigation("RentalCard");
                });

            modelBuilder.Entity("SuryoyoBibliotek.Model.RentalCard", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
